# Default values for gremlins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: gremlins
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
  namespace: devops

imagePullSecrets: []
nameOverride: gremlins
strategy: Rolling
replicas: 2
